server:
  port: 8081

spring:
  datasource:
    url: jdbc:h2:tcp://localhost:9093/account;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    userName: sa
    password:
    driver-class-name: org.h2.Driver
    platform: h2
    initialize: true
    continue-on-error: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
      hbm2ddl:
        auto: update
  h2:
    console:
      path: /db-console

eureka:
  client:
    enabled: false