spring:
  datasource:
    url: jdbc:h2:tcp://database-server:9093/account;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/