CREATE TABLE USER
  (
  USER_NAME VARCHAR(20) NOT NULL,
  PASSWORD VARCHAR(40) NOT NULL,
  PRIMARY KEY (USER_NAME)
  );

CREATE TABLE ACCOUNT
  (
  NAME VARCHAR(20) NOT NULL,
  LAST_SEEN TIMESTAMP,
  NOTE VARCHAR(20000),
  PRIMARY KEY (NAME)
  );
