spring:
  datasource:
#    url: jdbc:h2:tcp://localhost:9093/metadata;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    url: jdbc:h2:file:~/test
    userName: sa
    password:
    driver-class-name: org.h2.Driver
    platform: h2
  h2:
    console:
      enabled: true
      path: /db-console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
profiles:
     active: native

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus