server:
  port: 8082

spring:
  datasource:
    url: jdbc:h2:mem:metadata
    userName: sa
    password:
    driver-class-name: org.h2.Driver
    platform: h2
    initialization-mode: embedded
    continue-on-error: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    open-in-view: true
  h2:
    console:
      path: /db-console
  cloud:
    refresh:
      #TODO временное решение, ждем исправления https://github.com/spring-projects/spring-boot/issues/13042
      refreshable: false
  devtools:
    livereload:
      port: 35731
    restart:
      log-condition-evaluation-delta: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus