CREATE TABLE ENTITY
  (
  CODE VARCHAR(20) NOT NULL,
  PRIMARY KEY (CODE)
  );

CREATE TABLE ATTRIBUTE
  (
  CODE VARCHAR(20) NOT NULL,
  ENTITY VARCHAR(20) NOT NULL,
  PRIMITIVE VARCHAR(20) NOT NULL
  );