spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/gurv/vg
  devtools:
  livereload:
    port: 35734
    restart:
      log-condition-evaluation-delta: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus