version: '3.4'

services:
  config:
    image: gurv/vg-config:latest
    ports:
      - "8888:8888"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager