version: '3.4'

services:
  config:
    image: gurv/vg-config:latest
    ports:
      - "8888:8888"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  discovery:
    image: gurv/vg-discovery:latest
    ports:
      - "8761:8761"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  auth:
    image: gurv/vg-auth:latest
    ports:
      - "5000:8080"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  account:
    image: gurv/vg-account:latest
    ports:
      - "8081:8081"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  skipper:
    image: gurv/vg-skipper:latest
    ports:
      - "7577:7577"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  dataflow:
    image: gurv/vg-dataflow:latest
    ports:
      - "9393:9393"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  gateway:
    image: gurv/vg-gateway:latest
    ports:
      - "10000:10000"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  metadata:
    image: gurv/vg-metadata:latest
    ports:
      - "8082:8082"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
