version: '2'

services:
  config:
    build: ./config/build/docker
    ports:
      - 8888:8888

  discovery:
    build: ./discovery/build/docker

  gateway:
    build: ./gateway/build/docker

  database-data:
    build: ./database/data

  database-server:
    build: ./database/server
    ports:
      - 8082:8082 # web
      - 9092:9092 # tcp

  auth:
    build: ./auth/build/docker
    ports:
      - 5000:5000

  account:
    build: ./account/build/docker
    ports:
      - 6000:6000

  metadata:
    build: ./metadata/build/docker
    ports:
      - 8081:8081

  web:
    build: ./web
