version: '2'

services:
  config:
    build: ./config/build/docker
    image: gurv/vg-config:latest
    container_name: vg_config
    ports:
      - 8888:8888

  discovery:
    build: ./discovery/build/docker
    image: gurv/vg-discovery:latest
    container_name: vg_discovery
    ports:
      - 8761:8761
    links:
      - config

  gateway:
    build: ./gateway/build/docker
    image: gurv/vg-gateway:latest
    container_name: vg_gateway
    ports:
     - 10000:10000
    links:
      - config
      - discovery

  auth:
    build: ./auth/build/docker
    image: gurv/vg-auth:latest
    container_name: vg_auth
    ports:
     - 5000:5000
    links:
      - database-server
      - config
      - discovery
      - gateway

  account:
    build: ./account/build/docker
    image: gurv/vg-account:latest
    container_name: vg_account
    ports:
     - 8081:8081
    links:
      - database-server
      - config
      - discovery
      - gateway
