version: '3.4'

services:
  config:
    build: ./config/build/docker
    image: gurv/vg-config:latest
    container_name: vg-config
    ports:
      - 8888:8888

  discovery:
    build: ./discovery/build/docker
    image: gurv/vg-discovery:latest
    container_name: vg-discovery
    ports:
      - 8761:8761
    links:
      - vg-config

  gateway:
    build: ./gateway/build/docker
    image: gurv/vg-gateway:latest
    container_name: vg-gateway
    ports:
     - 10000:10000
    links:
      - vg-config
      - vg-discovery

  auth:
    build: ./auth/build/docker
    image: gurv/vg-auth:latest
    container_name: vg-auth
    ports:
     - 5000:5000
    links:
      - vg-database-server-h2
      - vg-config
      - vg-discovery
      - vg-gateway

  account:
    build: ./account/build/docker
    image: gurv/vg-account:latest
    container_name: vg-account
    ports:
     - 8081:8081
    links:
      - database-server-h2
      - config
      - discovery
      - gateway
