version: '3.4'

services:
  dataflow:
    image: gurv/vg-dataflow:latest
    ports:
      - '9393:9393'
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
