spring:
  application:
    name: gateway
  devtools:
    livereload:
      port: 35733
    restart:
      log-condition-evaluation-delta: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus