server:
  port: 8084

documentation:
  swagger:
    services:
      -
        name: Sample Operation
        url: http://sample-operation/v2/swagger.json
        version: 2.0
      - 
        name: Human Service
        url: http://sample-account/v2/swagger.json
        version: 2.0