management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

spring:
  application:
    name: dataflow
  datasource:
    url: jdbc:h2:mem:dataflow