server:
  port: 6000
  context-path: /accounts

security:
  oauth2:
    client:
      clientId: account-service
#      clientSecret: ${ACCOUNT_SERVICE_PASSWORD}
      accessTokenUri: http://auth:5000/uaa/oauth/token
      grant-type: client_credentials
      scope: server

spring:
  datasource:
    url: jdbc:h2:tcp://database-server:9092/account;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    userName: sa
    password:
    driver-class-name: org.h2.Driver
    platform: h2

  h2:
    console:
      enabled: true
      path: /db-console

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
       ddl-auto: none
