server:
  port: 5000
  context-path: /uaa

spring:
  datasource:
    url: jdbc:h2:tcp://database-server:9092/auth;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    userName: sa
    password:
    driver-class-name: org.h2.Driver
    platform: h2
    initialize: true

  h2:
    console:
      enabled: true
      path: /console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      hbm2ddl:
        auto: true