server:
  port: 8084

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

documentation:
  swagger:
    services:
      -
        name: "Config"
        url: http://localhost:8888/v2/api-docs
        version: 2.0
      -
        name: "Account"
        url: http://localhost:8081/v2/api-docs
        version: 2.0
      -
        name: "Auth"
        url: http://localhost:5000/v2/api-docs
        version: 2.0
      -
        name: "Metadata"
        url: http://localhost:8082/v2/api-docs
        version: 2.0
      -
        name: "[sample] Operation"
        url: http://localhost:8101/v2/api-docs
        version: 2.0
      -
        name: "[sample] Account"
        url: http://localhost:8102/v2/api-docs
        version: 2.0