server:
  port: 8084

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

documentation:
  swagger:
    services:
      -
        name: "[sample] Operation"
        url: http://localhost:8101/v2/api-docs
        version: 2.0
      -
        name: "[sample] Account"
        url: http://localhost:8102/v2/api-docs
        version: 2.0