#TODO Официального docker-образа нет, поэтому вынужденная зависимость от 3-х лиц
# Полезное oб этом образе:
#   DockerHub: https://hub.docker.com/r/wurstmeister/kafka/
#   GitHub: https://github.com/wurstmeister/kafka-docker
#   Tutorial: http://wurstmeister.github.io/kafka-docker/
FROM wurstmeister/kafka

MAINTAINER Vladimir Gurinovich <vladimir.gurinovich@gmail.com>
