server:
  port: 8102
spring:
  cloud:
    stream:
      bindings:
        input:
          destination: operations
      kafka:
        binder:
          brokers: localhost:9092
  datasource:
    url: jdbc:h2:mem:sample-account
    userName: sa
    password:
    driver-class-name: org.h2.Driver
    platform: h2
    initialization-mode: embedded
    continue-on-error: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
      hbm2ddl:
        auto: update
    open-in-view: true
  h2:
    console:
      path: /db-console